[package]
name = "titan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3.1"
byteorder = "1.4.3"
smallvec = "1.10.0"
num = "0.4.0"
num-derive = "0.3.3"
num-traits = "0.2.15"
