use num_derive::{FromPrimitive, ToPrimitive};
use std::fmt::{Display, Formatter};

#[derive(Debug, Copy, Clone, PartialEq, Eq, ToPrimitive, FromPrimitive)]
pub enum RegisterSlot {
    Zero = 0,
    AssemblerTemporary = 1,
    Value0 = 2,
    Value1 = 3,
    Parameter0 = 4,
    Parameter1 = 5,
    Parameter2 = 6,
    Parameter3 = 7,
    Temporary0 = 8,
    Temporary1 = 9,
    Temporary2 = 10,
    Temporary3 = 11,
    Temporary4 = 12,
    Temporary5 = 13,
    Temporary6 = 14,
    Temporary7 = 15,
    Saved0 = 16,
    Saved1 = 17,
    Saved2 = 18,
    Saved3 = 19,
    Saved4 = 20,
    Saved5 = 21,
    Saved6 = 22,
    Saved7 = 23,
    Temporary8 = 24,
    Temporary9 = 25,
    Kernel0 = 26,
    Kernel1 = 27,
    GeneralPointer = 28,
    StackPointer = 29,
    FramePointer = 30,
    ReturnAddress = 31,
}

impl RegisterSlot {
    pub fn from_string(input: &str) -> Option<RegisterSlot> {
        Some(match input {
            "zero" => RegisterSlot::Zero,
            "at" => RegisterSlot::AssemblerTemporary,
            "v0" => RegisterSlot::Value0,
            "v1" => RegisterSlot::Value1,
            "a0" => RegisterSlot::Parameter0,
            "a1" => RegisterSlot::Parameter1,
            "a2" => RegisterSlot::Parameter2,
            "a3" => RegisterSlot::Parameter3,
            "t0" => RegisterSlot::Temporary0,
            "t1" => RegisterSlot::Temporary1,
            "t2" => RegisterSlot::Temporary2,
            "t3" => RegisterSlot::Temporary3,
            "t4" => RegisterSlot::Temporary4,
            "t5" => RegisterSlot::Temporary5,
            "t6" => RegisterSlot::Temporary6,
            "t7" => RegisterSlot::Temporary7,
            "s0" => RegisterSlot::Saved0,
            "s1" => RegisterSlot::Saved1,
            "s2" => RegisterSlot::Saved2,
            "s3" => RegisterSlot::Saved3,
            "s4" => RegisterSlot::Saved4,
            "s5" => RegisterSlot::Saved5,
            "s6" => RegisterSlot::Saved6,
            "s7" => RegisterSlot::Saved7,
            "t8" => RegisterSlot::Temporary8,
            "t9" => RegisterSlot::Temporary9,
            "k0" => RegisterSlot::Kernel0,
            "k1" => RegisterSlot::Kernel1,
            "gp" => RegisterSlot::GeneralPointer,
            "sp" => RegisterSlot::StackPointer,
            "fp" => RegisterSlot::FramePointer,
            "ra" => RegisterSlot::ReturnAddress,

            _ => return None,
        })
    }

    pub fn as_string(&self) -> &str {
        match self {
            RegisterSlot::Zero => "zero",
            RegisterSlot::AssemblerTemporary => "at",
            RegisterSlot::Value0 => "v0",
            RegisterSlot::Value1 => "v1",
            RegisterSlot::Parameter0 => "a0",
            RegisterSlot::Parameter1 => "a1",
            RegisterSlot::Parameter2 => "a2",
            RegisterSlot::Parameter3 => "a3",
            RegisterSlot::Temporary0 => "t0",
            RegisterSlot::Temporary1 => "t1",
            RegisterSlot::Temporary2 => "t2",
            RegisterSlot::Temporary3 => "t3",
            RegisterSlot::Temporary4 => "t4",
            RegisterSlot::Temporary5 => "t5",
            RegisterSlot::Temporary6 => "t6",
            RegisterSlot::Temporary7 => "t7",
            RegisterSlot::Saved0 => "s0",
            RegisterSlot::Saved1 => "s1",
            RegisterSlot::Saved2 => "s2",
            RegisterSlot::Saved3 => "s3",
            RegisterSlot::Saved4 => "s4",
            RegisterSlot::Saved5 => "s5",
            RegisterSlot::Saved6 => "s6",
            RegisterSlot::Saved7 => "s7",
            RegisterSlot::Temporary8 => "t8",
            RegisterSlot::Temporary9 => "t9",
            RegisterSlot::Kernel0 => "k0",
            RegisterSlot::Kernel1 => "k1",
            RegisterSlot::GeneralPointer => "gp",
            RegisterSlot::StackPointer => "sp",
            RegisterSlot::FramePointer => "fp",
            RegisterSlot::ReturnAddress => "ra",
        }
    }
}

impl Display for RegisterSlot {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(f, "${}", self.as_string())
    }
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, ToPrimitive, FromPrimitive)]
pub enum FPRegisterSlot {
    F0 = 0,
    F1 = 1,
    F2 = 2,
    F3 = 3,
    F4 = 4,
    F5 = 5,
    F6 = 6,
    F7 = 7,
    F8 = 8,
    F9 = 9,
    F10 = 10,
    F11 = 11,
    F12 = 12,
    F13 = 13,
    F14 = 14,
    F15 = 15,
    F16 = 16,
    F17 = 17,
    F18 = 18,
    F19 = 19,
    F20 = 20,
    F21 = 21,
    F22 = 22,
    F23 = 23,
    F24 = 24,
    F25 = 25,
    F26 = 26,
    F27 = 27,
    F28 = 28,
    F29 = 29,
    F30 = 30,
    F31 = 31,
}
impl FPRegisterSlot {
    pub fn from_string(input: &str) -> Option<FPRegisterSlot> {
        Some(match input {
            "f0" => FPRegisterSlot::F0,
            "f1" => FPRegisterSlot::F1,
            "f2" => FPRegisterSlot::F2,
            "f3" => FPRegisterSlot::F3,
            "f4" => FPRegisterSlot::F4,
            "f5" => FPRegisterSlot::F5,
            "f6" => FPRegisterSlot::F6,
            "f7" => FPRegisterSlot::F7,
            "f8" => FPRegisterSlot::F8,
            "f9" => FPRegisterSlot::F9,
            "f10" => FPRegisterSlot::F10,
            "f11" => FPRegisterSlot::F11,
            "f12" => FPRegisterSlot::F12,
            "f13" => FPRegisterSlot::F13,
            "f14" => FPRegisterSlot::F14,
            "f15" => FPRegisterSlot::F15,
            "f16" => FPRegisterSlot::F16,
            "f17" => FPRegisterSlot::F17,
            "f18" => FPRegisterSlot::F18,
            "f19" => FPRegisterSlot::F19,
            "f20" => FPRegisterSlot::F20,
            "f21" => FPRegisterSlot::F21,
            "f22" => FPRegisterSlot::F22,
            "f23" => FPRegisterSlot::F23,
            "f24" => FPRegisterSlot::F24,
            "f25" => FPRegisterSlot::F25,
            "f26" => FPRegisterSlot::F26,
            "f27" => FPRegisterSlot::F27,
            "f28" => FPRegisterSlot::F28,
            "f29" => FPRegisterSlot::F29,
            "f30" => FPRegisterSlot::F30,
            "f31" => FPRegisterSlot::F31,
            _ => return None,
        })
    }

    pub fn as_string(&self) -> &str {
        match self {
            FPRegisterSlot::F0 => "f0",
            FPRegisterSlot::F1 => "f1",
            FPRegisterSlot::F2 => "f2",
            FPRegisterSlot::F3 => "f3",
            FPRegisterSlot::F4 => "f4",
            FPRegisterSlot::F5 => "f5",
            FPRegisterSlot::F6 => "f6",
            FPRegisterSlot::F7 => "f7",
            FPRegisterSlot::F8 => "f8",
            FPRegisterSlot::F9 => "f9",
            FPRegisterSlot::F10 => "f10",
            FPRegisterSlot::F11 => "f11",
            FPRegisterSlot::F12 => "f12",
            FPRegisterSlot::F13 => "f13",
            FPRegisterSlot::F14 => "f14",
            FPRegisterSlot::F15 => "f15",
            FPRegisterSlot::F16 => "f16",
            FPRegisterSlot::F17 => "f17",
            FPRegisterSlot::F18 => "f18",
            FPRegisterSlot::F19 => "f19",
            FPRegisterSlot::F20 => "f20",
            FPRegisterSlot::F21 => "f21",
            FPRegisterSlot::F22 => "f22",
            FPRegisterSlot::F23 => "f23",
            FPRegisterSlot::F24 => "f24",
            FPRegisterSlot::F25 => "f25",
            FPRegisterSlot::F26 => "f26",
            FPRegisterSlot::F27 => "f27",
            FPRegisterSlot::F28 => "f28",
            FPRegisterSlot::F29 => "f29",
            FPRegisterSlot::F30 => "f30",
            FPRegisterSlot::F31 => "f31",
        }
    }
}
impl Display for FPRegisterSlot {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(f, "${}", self.as_string())
    }
}
